In [1]:
import pandas as pd
marks = pd.read_csv('https://query.data.world/s/HqjNNadqEnwSq1qnoV_JqyRJkc7o6O')

In [2]:
marks.head(100)

    Prefix  Assignment  Tutorial  Midterm  TakeHome   Final
0        5       57.14     34.09    64.38     51.48   52.50
1        8       95.05    105.49    67.50     99.07   68.33
2        8       83.70     83.17    30.00     63.15   48.89
3        7       81.22     96.06    49.38    105.93   80.56
4        8       91.32     93.64    95.00    107.41   73.89
5        7       95.00     92.58    93.12     97.78   68.06
6        8       95.05    102.99    56.25     99.07   50.00
7        7       72.85     86.85    60.00       NaN   56.11
8        8       84.26     93.10    47.50     18.52   50.83
9        7       90.10     97.55    51.25     88.89   63.61
10       7       80.44     90.20    75.00     91.48   39.72
11       6       86.26       NaN      NaN     87.59   77.50
12       8       97.16       NaN      NaN     93.52   63.33
13       7       91.28       NaN      NaN     99.81   92.22
14       8       84.80       NaN      NaN     16.91   35.83
15       7       93.83     95.43    88.12     80.93   90.00
16       8       84.80     89.08    47.50     16.91   53.33
17       4       92.01    102.52    38.75     86.11   49.17
18       8       55.14     81.85    75.00     56.11   62.50
19       8       93.04     82.93    79.38     83.33   91.11
20       8       63.40     86.21    63.12     72.78     NaN
21       8       75.27     97.52    63.12     61.11   66.11
22       8       63.78     76.21    39.38     42.22   34.44
23       7       80.44     90.20      NaN     91.48   72.22
24       7       53.36     82.01      NaN    102.59   56.39
25       6       91.28     95.24      NaN     97.59   92.78
26       8       82.45     86.65      NaN     85.56   89.17
27       8       75.27     86.67    69.38     61.11   88.89
28       8       91.32     94.89    76.25    107.41   85.56
29       7       91.62     65.18    71.88     90.00   45.56
..     ...         ...       ...      ...       ...     ...
69       8       80.53     92.80    51.25     72.78   66.67
70       8       90.98     97.55    86.25     88.89   90.00
71       8       93.59    103.83    92.50     96.85   87.22
72       8       97.33    100.42    69.38    102.59   83.06
73       7         NaN       NaN      NaN       NaN     NaN
74       8       84.26     96.66    52.50     83.33   50.00
75       7       93.83    102.19   106.25     94.44  102.78
76       8       75.27     86.67    70.00     71.85   80.00
77       8       92.02    100.58    73.12     63.89   65.28
78       8       97.16    103.71    83.75     95.93   78.89
79       8       66.17     93.68    71.88     42.22   61.39
80       8       81.22     91.95    79.38    105.93   90.00
81       7       74.29     65.70    78.75    103.52   55.00
82       8       97.33    106.74    76.88    108.89   83.89
83       4       86.86     62.64    92.50     85.19   62.78
84       6       95.60     61.40    64.38     99.81   42.78
85       4       87.93     99.47    53.12     87.96   61.11
86       6       98.49     95.43    42.50     24.77   39.44
87       7       74.35     92.93    86.25     78.70   73.89
88       7       86.29     88.81    83.12     77.96   75.83
89       8       97.00    100.52    64.38     90.74   58.61
90       8         NaN       NaN      NaN       NaN     NaN
91       8       96.41    103.71    56.25     95.93   66.39
92       7       95.60     82.28    76.88    108.33   78.33
93       8       87.52     91.58    56.25     71.85   85.00
94       8       96.73    103.71    45.00     93.52   61.94
95       7       85.34     80.54    41.25     93.70   39.72
96       8       89.94    102.77    87.50     90.74   87.78
97       7       95.60     76.13    66.25     99.81   85.56
98       8       63.40     97.37    73.12     72.78   77.22

[99 rows x 6 columns]

In [ ]:
#Count the number of missing values in each column of the dataset 'marks'.